---

- hosts: localhost
  connection: local
  roles:
    - role: indigo-dc.galaxycloud-tools
      galaxy_flavor: "galaxy-testing"
      galaxy_admin_api_key: "admin_api_key"
      when: galaxy_flavor != "galaxy-no-tools"
