---

- hosts: localhost
  connection: local
  roles:
  - role: indigo-dc.galaxycloud-refdata
    get_refdata: 'true'
    refdata_dir: '/cvmfs'
    refdata_cvmfs_configuration: 'cvmfs_preconfigured'
    refdata_cvmfs_repository_name: 'elixir-italy.galaxy.refdata'
    refdata_cvmfs_key_file: 'elixir-italy.galaxy.refdata.pub'
